---
title: "Using the while() and case_when() functions"
author: "Alex Ehrens"
date: "2/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# attach packages
library(tidyverse)
```

### Using the while() loop function for compound interest

```{r}
# initial conditions - set values for initial investment, interest rate, amount of times compounded annually, number of years, and target balance
balance = 1
interest_rate = 0.02
compound_per_yr = 1
yr = 0
target = 20000

source(here("Assignments", "R", "interest_while_fun.R"))

# return values for the amount of money and years it takes to reach the target balance in the account
balance
yr

# make data frame of results
interest_results <- data.frame(balance, yr)
```

### Using a case_when() function for Air Quality Index levels
```{r}
# generate data to test function
pm2.5_conc = runif(min = 1, max = 400, n = 30)

# source Air quality index function
source(here("Assignments", "R", "air_quality_function.R"))

# run function for generated PM2.5 concentration data
index_levels <- air_quality_index(pm2.5_conc = pm2.5_conc)

# print results
index_levels

# make dataframe showing index levels with sample PM2.5 concentrations
air_quality_results <- data.frame(pm2.5_conc, index_levels)
```

```{r}
### test function with samples of low and high distributions of values
# low PM2.5 concentrations
pm2.5_conc_low <- runif(min = 1, max = 100, n = 30)

# run function for generated PM2.5 concentration data
index_levels_low <- air_quality_index(pm2.5_conc = pm2.5_conc_low)

index_levels_low

# high PM2.5 concentrations
pm2.5_conc_high <- runif(min = 250, max = 500, n = 30)

# run function for generated PM2.5 concentration data
index_levels_high <- air_quality_index(pm2.5_conc = pm2.5_conc_high)

index_levels_high
```

### END ASSIGNMENT 3